a= int(input('Dla ilu osob chcesz zrobic salatke?  '))
g= int(input('ile pomidora?  '))
d= int(input('ile salaty?  '))
s = int(input('ile ogorka?  '))
print('ilosc pomidorow ',g*a)
print('ilosc salaty ',d*a)
print('ilosc ogorkow ',s*a)